language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.3.3
      env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - composer selfupdate
  - composer update $COMPOSER_FLAGS

script:
  - ./vendor/bin/behat -fprogress
  - ./vendor/bin/phpspec run -fdot
